ALL_COLUMNS = {
    "Symbol": {"label":"Symbol"},
    "Verdict": {"label":"Verdict"},
    "Actions": {"label": "Trade Now"},
    "Score": {"label":"Conviction", "type":"progress", "min":0, "max":100},
    "Price": {"label":"Price ₹", "format":"₹%.2f"},
    "RSI": {"label":"RSI", "format":"%.1f"},
    "News": {"label":"News"},
    "Events": {"label":"Events"},
    "Sector": {"label":"Sector"},
    "Position_Qty": {"label":"Qty", "format":"%d"},
    "Stop_Loss": {"label":"SL Price", "format":"₹%.2f"},
    "Target_10D": {"label":"10D Target", "format":"₹%.2f"},
    "Analysts": {"label":"Analyst Count", "format":"%d"},
    "Tgt_High": {"label":"High Target", "format":"₹%d"},
    "Tgt_Median": {"label":"Median Target", "format":"₹%d"},
    "Tgt_Low": {"label":"Low Target", "format":"₹%d"},
    "Tgt_Mean": {"label":"Mean Target", "format":"₹%d"},
    "Dispersion_Alert": {"label":"Dispersion"},
    "Ret_30D": {"label":"30D Backtest", "format":"%.2f%%"},
    "Ret_60D": {"label":"60D Backtest", "format":"%.2f%%"},
    "Ret_90D": {"label":"90D Backtest", "format":"%.2f%%"},
    "Strategy": {"label": "Strategy"},
    "Buy_Zone": {"label": "Buy Zone"},
    "Steam_Left": {"label": "Steam Left ₹", "format": "₹%.2f"},
    "Days_To_Target": {"label": "Est. Days", "format": "%.1f"},
    "Resilience": {"label": "War/News Resilience"},
    "Gap_Integrity": {"label": "Gap Integrity"},
    "Velocity": {"label": "Momentum Velocity", "format": "%.2f%%"},
    "Ret_7D": {"label": "7D Return", "format": "%.2f%%"},
    "Technical_Score": {"label":"Technical", "type":"progress", "min":0, "max":100},
    "Fundamental_Score": {"label":"Fundamental", "type":"progress", "min":0, "max":100},
    "Sentiment_Score": {"label":"Sentiment", "type":"progress", "min":0, "max":100},
    "Context_Score": {"label":"Context/RS/MTF", "type":"progress", "min":0, "max":100},
    "Score_Pre_Regime": {"label":"Pre-Regime Score", "format":"%.2f"},
    "Regime": {"label":"Market Regime"},
    "Regime_Multiplier": {"label":"Regime x", "format":"%.2f"},
    "India_VIX": {"label":"India VIX", "format":"%.2f"},
    "RS_Rank": {"label":"RS Rank %", "format":"%.2f"},
    "RS_3M": {"label":"RS 3M", "format":"%.3f"},
    "RS_6M": {"label":"RS 6M", "format":"%.3f"},
    "RS_12M": {"label":"RS 12M", "format":"%.3f"},
    "RS_Composite": {"label":"RS Composite", "format":"%.3f"},
    "Vol_Adj_Mom": {"label":"Vol Adj Mom", "format":"%.2f"},
    "EMA200_Extension_Pct": {"label":"EMA200 Extension", "format":"%.2f%%"},
    "Quality_Gate_Failures": {"label":"Quality Gates"},
    "Avoid_Flag": {"label":"Avoid"}
}
