ALL_COLUMNS = {
    "Symbol": {"label":"Symbol"},
    "Verdict": {"label":"Verdict"},
    "Actions": {"label": "Trade Now"},
    "Score": {"label":"Conviction", "type":"progress", "min":0, "max":100},
    "Price": {"label":"Price ₹", "format":"₹%.2f"},
    "RSI": {"label":"RSI", "format":"%.1f"},
    "News": {"label":"News"},
    "Events": {"label":"Events"},
    "Sector": {"label":"Sector"},
    "Position_Qty": {"label":"Qty", "format":"%d"},
    "Stop_Loss": {"label":"SL Price", "format":"₹%.2f"},
    "Target_10D": {"label":"10D Target", "format":"₹%.2f"},
    "Analysts": {"label":"Analyst Count", "format":"%d"},
    "Tgt_High": {"label":"High Target", "format":"₹%d"},
    "Tgt_Median": {"label":"Median Target", "format":"₹%d"},
    "Tgt_Low": {"label":"Low Target", "format":"₹%d"},
    "Tgt_Mean": {"label":"Mean Target", "format":"₹%d"},
    "Dispersion_Alert": {"label":"Dispersion"},
    "Ret_30D": {"label":"30D Backtest", "format":"%.2f%%"},
    "Ret_60D": {"label":"60D Backtest", "format":"%.2f%%"},
    "Ret_90D": {"label":"90D Backtest", "format":"%.2f%%"},
    "Strategy": {"label": "Strategy"},
    "Buy_Zone": {"label": "Buy Zone"},
    "Steam_Left": {"label": "Steam Left ₹", "format": "₹%.2f"},
    "Days_To_Target": {"label": "Est. Days", "format": "%.1f"},
    "Resilience": {"label": "War/News Resilience"},
    "Gap_Integrity": {"label": "Gap Integrity"},
    "Velocity": {"label": "Momentum Velocity", "format": "%.2f%%"},
    "Ret_7D": {"label": "7D Return", "format": "%.2f%%"}
}
